#!/bin/bash

DOTFILES=$HOME/dotfiles

declare -a arr=(".bashrc" 
    ".bash_profile"
    ".Xresources"
    ".xinitrc"
		".inputrc"
		".config/motd.sh"
		".config/i3"
		".config/i3blocks"
		".config/nvim"
		".config/chromium-flags.conf"
		".config/archey3"
		".gitconfig"
                )

function link_file(){
  LINK="$HOME/$1"
  TARGET="$DOTFILES/home/$1"
  if [ -f $LINK ]; then
    echo "Replace file '$1'?"
    read -p "[y/N]?: " Q_REPLACE_FILE
    if [[ $Q_REPLACE_FILE == 'y' ]]; then
      ln -sf $TARGET $LINK
      ls -la $LINK
    fi
  elif [ -d $LINK ]; then
    echo "Replace directory '$1'?"
    read -p "[y/N]: " Q_REPLACE_DIR
    if [[ $Q_REPLACE_DIR == 'y' ]]; then
      rm -rf $LINK
      ln -sf $TARGET $LINK
      ls -la $LINK
    fi
  else
    ln -s $TARGET $LINK
    ls -la $LINK
  fi
}

for i in "${arr[@]}"
do
  link_file "$i"
done

pacman -Qe | awk -F" " '{print $1}' > $DOTFILES/pacman.list
